services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/workspace
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - front-tier
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  front-tier: {}